### ISSUE TITLE
Feature Request: reset list

### ISSUE THREAD

**Issue by scheunengeist** [SecUSo/privacy-friendly-shopping-list#16]
First off, good work on the app so far, it's looking very promising!

I like the "move to bottom" functionality within the lists, it helps keep things tidy. However, when I'm done shopping, I need to reactivate all items one by one. In case of larger connected item groups (e. g. non-trivial recipes), when I will need all or most of the items again next time, this might be improved by providing a "list reset", by which all items will be made active again.

This issue is related to parts of #13, and will be most effective in conjunction with #6. :)
Thanks for considering!

**Comment by Yonjuni** [comment]
That could be done in the dialog where now the list can be edited, duplicated, shared or deleted.

**Comment by scheunengeist** [comment]
My apologies for not seeing this earlier. Thanks for implementing! I can't test it yet since there's no updated f-droid package and I don't presently build myself, but I'll make sure I check it out as soon as possible. Thanks!

**Comment by Ifill-Brito** [comment]
You're welcome. Thanks for helping improving the app by giving us your feedback!

**Comment by Yonjuni** [comment]
The update will be in F-Droid within the next two weeks.

**Comment by Yonjuni** [comment]
@scheunengeist We have just submitted the update (version 1.0.6) to F-Droid.
