### ISSUE TITLE
"+" button disappears and doesn't come back when scrolling long lists

### ISSUE THREAD

**Issue by vedvyas** [SecUSo/privacy-friendly-shopping-list#36]
Steps to reproduce:
1. Visit the list of shopping lists or a specific shopping list. Whichever you choose, it should have enough items to require scrolling down to see all of them.
2. Start to scroll down. The "+" button in the bottom right immediately disappears.
3. Scroll up and down the list. 

What is observed: the "+" button doesn't reappear until you leave the list and re-enter it.

This happens with version 1.0.7 (installed from F-Droid) on an Android 6.0.1 device in either orientation.

**Comment by Ifill-Brito** [comment]
Thanks for reporting this bug. It will be fixed in the next release.

**Comment by vedvyas** [comment]
Thanks!
