### ISSUE TITLE
autorotation, font-size

### ISSUE THREAD

**Issue by paulle** [SecUSo/privacy-friendly-shopping-list#5]
First thanks to all, developping this app.
Found 2 issues, first autorotation don't work (can't use the app 'horizontal'). Font size cannot be changed. For people with bad eyes this will be an issue.
Best regards Paulle

**Comment by Yonjuni** [comment]
Thanks for the comment. 
The limitation to the portrait mode was a design decision, but we can add it to future features. 
What do you mean by changing the font size? Should it be changeable in the app or should it adapt if the device uses a bigger font size?

**Comment by paulle** [comment]
Thank you for answering so fast. Changing the font size within the app or adapting the font size of the device, both possibilities are fine. As I nothing know about programming, l think the developer should decide. The developer can choose the better and maybe less time consuming solution.
Best regards and thank you.

Am 10. November 2016 16:24:56 MEZ, schrieb Karola Marky <notifications@github.com>:
>Thanks for the comment. 
>The limitation to the portrait mode was a design decision, but we can
>add it to future features. 
>What do you mean by changing the font size? Should it be changeable in
>the app or should it adapt if the device uses a bigger font size? 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SecUSo/privacy-friendly-shopping-list/issues/5#issuecomment-259718402

-- 
K-9 Mail

**Comment by Yonjuni** [comment]
The font size should adjust in the new version 1.0.5
