### ISSUE TITLE
[Question] How do I run DataBaseConfig class?

### ISSUE THREAD

**Issue by jdvr** [SecUSo/privacy-friendly-shopping-list#75]
I have been trying to run with rigth click on Android Studio but it just make gradle fail with `SourceSets main not found`

**Comment by Kamuno** [comment]
We are using ormlite as orm for the database. I am unsure what exactly your issue is exactly. Can you maybe post the detailed error message why it is failing? Maybe you can also check the ormlite documentation for help.

**Comment by jdvr** [comment]
I have solved the problem using a grade task. No more problems.
